### PR TITLE
LPS-125731 NoClassDefFoundError is thrown when uploading documents with MS Visio content

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Adding the curvesapi library solves the issue.

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The copyright SF failures are fixed by https://github.com/liferay/liferay-portal/commit/a4213bf87dba58f2d03380fccbc1b110d9be2119#diff-6d2d9d9e926cc94ac5487d77eb5eec8b3bb07ea52f89020c6056884d7a3fe482, re-run it.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The above commerce SF failures have been fixed here: [COMMERCE-5471](https://issues.liferay.com/browse/COMMERCE-5471)

**Comment by Hanlf** [comment]
New SF issue on upstream: [LRQA-64391](https://issues.liferay.com/browse/LRQA-64391)

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward
